[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
stock_lend = "8MFfkTvA13QJKue1k8qwFqaPFxJm9qiJDYPoRUtvoZ3Z"

[programs.devnet]
stock_lend = "8MFfkTvA13QJKue1k8qwFqaPFxJm9qiJDYPoRUtvoZ3Z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"